country: china
province: beijing
city: beijing
area: haidian
a:
  b:
    c:
      e: 123
likes:
  - game
  - music

user1:
  name: kang
  age: 16

datasource:
  driver: com.mysql.jdbc.driver
  url: jdbc:mysql://localhost/springboot
  username: root
  password: root666